service:
  port: ":3000"                 # 服务运行的端口号
  secret_key: "your_secret_key" #auth密钥
  api_key:  "your api key"      #api 密钥
  csrf_key: "your csrf key"     #csrf请求保护密钥
  white_url:
    - /api/v1/captcha
    - /api/register
    - /api/login

mysql:
  username: "root"           # MySQL用户名
  password: "123456"  # MySQL密码
  host: "192.168.245.22"          # MySQL主机地址
  port: "3306"               # MySQL端口
  database: "go_api_gateway"  # MySQL数据库名称
  charset: "utf8mb4"         # MySQL字符集
  timeout: 30                # MySQL连接超时（秒）
  pool:
    max_open_conns: 20  # 最大打开连接数
    max_idle_conns: 18  # 最大空闲连接数
    conn_max_lifetime: 600  # 连接的最大生命周期（秒）

redis:
  username: "default"        # Redis用户名
  password: "your_password"  # Redis密码
  host: "localhost"          # Redis主机地址
  port: "6379"               # Redis端口
  db: 0                      # Redis数据库索引
  poolsize: 10               # Redis连接池大小
  maxRetries: 3              # 最大重试次数

rabbitmq:
  url: "amqp://localhost"    # RabbitMQ连接URL
  username: "guest"          # RabbitMQ用户名
  password: "guest"          # RabbitMQ密码
  host: "localhost"          # RabbitMQ主机地址
  port: "5672"               # RabbitMQ端口
  pool:
    max_channels: 10  # 最大 RabbitMQ 信道数
    max_idle_channels: 5  # 最大空闲信道数

casbin:
  type: "file"               # Casbin配置类型
  username: ""               # Casbin用户名（如果需要）
  password: ""               # Casbin密码（如果需要）
  host: "localhost"          # Casbin主机地址
  port: "3306"               # Casbin端口
  database: "casbin_db"      # Casbin数据库名称
  exist: true                # 是否存在

etcd:
  host: "localhost"          # Etcd主机地址
  port: "2379"               # Etcd端口

clickhouse:
  host: "localhost"          # Clickhouse主机地址
  port: "8123"               # Clickhouse端口
  name: "default"            # Clickhouse用户名
  password: ""               # Clickhouse密码
  database: "click_db"       # Clickhouse数据库名称

log:
  log_path: "./logs" # 日志文件路径
  link_name: "latest"     # 日志链接名称
  log_level: "INFO"            # 日志级别（DEBUG, INFO, WARN, ERROR）

captcha:
  prefix: "captcha"           # 验证码前缀
  limit:  "50"
  expired: "5m"               # 验证码过期时间（使用 Go 的 `time.Duration` 格式）

postgresql:
  host: "localhost"           # PostgreSQL主机地址
  port: "5432"                # PostgreSQL端口
  database: "your_db"         # PostgreSQL数据库名称
  user: "your_user"           # PostgreSQL用户名
  password: "your_password"   # PostgreSQL密码
  pool:
    max_open_conns: 20  # 最大打开连接数
    max_idle_conns: 18  # 最大空闲连接数
    conn_max_lifetime: 600  # 连接的最大生命周期（秒）

mongo:
  ip: "localhost"             # MongoDB主机地址
  port: "27017"               # MongoDB端口
  database: "your_db"         # MongoDB数据库名称
  pool:
    max_pool_size: 20  # MongoDB 最大连接池大小
    min_pool_size: 10   # MongoDB 最小连接池大小